server:
  port: 9003

spring:
  application:
    name: keanntech-provider-admin

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.12.128:3306/keanntech_admin?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    name: keanntech
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 30000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: select '1' from dual
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-open-prepared-statements: 20
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall,log4j

  redis:
    host: 192.168.12.129
    password: 123456
    timeout: 10000
    database: 0
    lettuce:
      pool:
        max-active: 10
        max-wait: -1
        min-idle: 0
        max-idle: 10


mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.keanntech.common.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
    map-underscore-to-camel-case: true
    use-generated-keys: true
    default-executor-type: reuse
    defaultStatementTimeout: 1000
    jdbc-type-for-null: null
    call-setters-on-nulls: true
  global-config:
    db-config:
      logic-not-delete-value: 1
      logic-delete-value: 0

ignore:
  authUrls:
    - /oauth/**
    - /actuator/**
    - /druid/**
    - /v2/api-docs
    - /swagger-ui.html
    - /swagger-resources/**
  webUnInterceptUris: /v2/api-docs,/swagger-ui.html,/swagger-resources/**,/webjars/**,/oauth/**,/actuator/**,/druid/**

feign:
  httpclient:
    enabled: true

ribbon:
  MaxAutoRetries: 3
  MaxAutoRetriesNextServer: 0
  ReadTimeout: 5000

keanntech:
  feignUrl:
    provider:
      admin: http://127.0.0.1:9003