server:
  port: 9000
spring:
  application:
    name: keanntech-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allow-credentials: true
            allowed-origins: "*"
            allowed-headers: "*"
            allowed-methods: "*"
            max-age: 3600
      routes:
      - id: gateway-route-authorization
        uri: ${keanntech.feignUrl.provider.auth}
        predicates:
         - Path=/oauth/**
      - id: gateway-route-provider-admin
        uri: ${keanntech.feignUrl.provider.admin}
        predicates:
         - Path=/api/admin/**


ignore:
  authUrls:
    - /oauth/

keanntech:
  feignUrl:
    provider:
      admin: http://127.0.0.1:9003
      auth: http://127.0.0.1:9001